dataSource: /Users/slincastro/Projects/GitDataAnalisis/jsonData/
projects:
  - project:
      type : Win-Service
      name : AliquotNormalizationWinService
      path : /Users/slincastro/Projects/IDT/WinSvc-FormulationsOrderConverter
